# Generated by Django 5.2.1 on 2025-05-18 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.alumno'),
        ),
        migrations.AddField(
            model_name='matriculacion',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.gestion'),
        ),
        migrations.AddConstraint(
            model_name='nivel',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('numero__lte', 6)), name='check_nivel_numero'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.nivel'),
        ),
        migrations.AddField(
            model_name='profesormateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.materia'),
        ),
        migrations.AddField(
            model_name='profesormateria',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profesor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.profesormateria'),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.gestion'),
        ),
        migrations.AddField(
            model_name='horario',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.trimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculacion',
            unique_together={('alumno', 'gestion')},
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.CheckConstraint(condition=models.Q(('letra__in', ['A', 'B'])), name='check_grupo_letra'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('nivel', 'letra')},
        ),
        migrations.AlterUniqueTogether(
            name='profesormateria',
            unique_together={('profesor', 'materia')},
        ),
        migrations.AddConstraint(
            model_name='trimestre',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('numero__lte', 3)), name='check_trimestre_numero'),
        ),
        migrations.AlterUniqueTogether(
            name='trimestre',
            unique_together={('gestion', 'numero')},
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__gte', 1), ('dia_semana__lte', 5)), name='check_dia_semana'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__gte', '07:15:00'), ('hora_inicio__lt', '13:00:00')), name='check_hora_inicio'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', '07:15:00'), ('hora_fin__lte', '13:00:00')), name='check_hora_fin'),
        ),
    ]
